
--REQUIRED TABLE CREATION

--TABLE FOR 2018 DATA

CREATE TABLE data_2018 AS
SELECT *
FROM healthcare
WHERE EXTRACT(YEAR FROM date_of_admission)='2018'

--TABLE FOR 2019 DATA

CREATE TABLE data_2019 AS
SELECT *
FROM healthcare
WHERE EXTRACT(YEAR FROM date_of_admission)='2019'

--TABLE FOR 2020 DATA

CREATE TABLE data_2020 AS
SELECT *
FROM healthcare
WHERE EXTRACT(YEAR FROM date_of_admission)='2020'


--TABLE FOR 2021 DATA

CREATE TABLE data_2021 AS
SELECT *
FROM healthcare
WHERE EXTRACT(YEAR FROM date_of_admission)='2021'


--TABLE FOR 2022 DATA

CREATE TABLE data_2022 AS
SELECT *
FROM healthcare
WHERE EXTRACT(YEAR FROM date_of_admission)='2022'

--TABLE FOR 2023 DATA

CREATE TABLE data_2023 AS
SELECT *
FROM healthcare
WHERE EXTRACT(YEAR FROM date_of_admission)='2023'
